eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:password@registry:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  eureka:
    enable: true
  ReadTimeout: 5000
  ConnectTimeout: 5000

spring:
  rabbitmq:
    host: rabbitmq
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"

authserver:
    hostname: auth-service
    port: 5000
    contextPath: /auth
      
server:
  port: 8080

name: zhangxd

security:
  user:
    name: user
    password: password
  oauth2:
    client:
      clientId: svca-service
      clientSecret: ${security.user.password}
      accessTokenUri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}